### ISSUE TITLE
std input does not work

### ISSUE THREAD

**Issue by proabiral** [trickest/dsieve#12]
#### Problem description
The tool does not work when domains are passed through std input.

<img width="990" alt="Screen Shot 2022-10-13 at 13 45 19" src="https://user-images.githubusercontent.com/22173232/195537541-4f376fe4-bc95-4d87-a2dd-778f132cd932.png">

#### Steps to reproduce
`cat <subdomain file> | dsieve -f 2`

**Comment by mhmdiaa** [comment]
Hi @proabiral,

This functionality was added in `v1.2`. Can you make sure your dsieve installation is up to date?

**Comment by proabiral** [comment]
Hello @mhmdiaa ,

Thank you for the quick response. 

`@latest` was pulling `v1.1.1` . Installing with `@master` , fixed the issue.

<img width="921" alt="Screen Shot 2022-10-14 at 12 02 06" src="https://user-images.githubusercontent.com/22173232/195775812-8a1d7519-eb4b-4587-869f-67ae4660358b.png">

**Comment by mhmdiaa** [comment]
It looks like this was caused by a formatting error in this release's tag, causing go to revert to the previous version. I just fixed it, and `go install` should start pulling the correct version.

Thanks for the heads up!
